(define (problem apenasmovimento)
	(:domain nossomercadinho )
	(:objects c1 c2 c3 c4 c5 - local
                  lbrigadeiro lcafezinho - lista
                  cont1 cont2 cont3 cont4 cont5 - contador
                  cafe bolodefuba bolacha amendoim feijao cm arroz - objeto 
                  lc cl cep mantega granulado - objeto )

	(:init
                (menorque cont4 cont5)
                (menorque cont3 cont4)
                (menorque cont2 cont3)
                (menorque cont1 cont2)
                (contadorem cont5)
                (produto bolacha c5)
	        (produto bolodefuba c1)
		(produto lc c4)
		(produto cafe c2)
		(produto cl c4)
		(produto cep c2)
		(produto mantega c5)
		(produto amendoim c3)
		(produto granulado c1)
		(produto feijao c2)
		(produto cm c1)
		(produto arroz c5)
		(corredor c5)
		(adjacentes c1 c4)
		(adjacentes c4 c1)
		(adjacentes c2 c5)
		(adjacentes c4 c5)
		(adjacentes c5 c4)
		(adjacentes c5 c2)
		(adjacentes c1 c2)
		(adjacentes c2 c1)
		(adjacentes c2 c3)
		(adjacentes c3 c2)
                (listadecompras lbrigadeiro lc)
                (listadecompras lbrigadeiro mantega)
                (listadecompras lbrigadeiro cl)
                (listadecompras lbrigadeiro granulado)
                (listadecompras lbrigadeiro cep)
                (listadecompras lcafezinho cafe)
                (listadecompras lcafezinho bolodefuba)
                (listadecompras lcafezinho bolacha)
                (listadecompras lcafezinho mantega)
                (= (total-cost) 0)
                )
	(:goal (and (forall (?l - lista) (listavencida ?l)) ))
        (:metric minimize (total-cost))
)
